const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; let mode='login', user=null, selectedMonths=5, calDate=new Date();
    function applyTheme(theme){document.body.classList.toggle('dark',theme==='dark');localStorage.setItem('orbit-theme',theme);const b=$('#themeToggle');if(b)b.textContent=theme==='dark'?'☀ Light':'☾ Dark'}
    applyTheme(localStorage.getItem('orbit-theme')||'light');
    const key='orbit-study-users'; const read=()=>JSON.parse(localStorage.getItem(key)||'{}'); const save=d=>localStorage.setItem(key,JSON.stringify(d)); const today=()=>new Date().toISOString().slice(0,10); const fmtDate=d=>new Intl.DateTimeFormat('en',{month:'long',day:'numeric',year:'numeric'}).format(d);
    function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
    function blankData(email){return {email,created:new Date().toISOString(),plans:[],completed:{}}}
    function authMode(){const signup=mode==='signup';$('#authTitle').textContent=signup?'Create your study space':'Welcome back';$('#authSub').textContent=signup?'Your goals and streaks stay with your account.':'Continue your momentum.';$('#authSubmit').textContent=signup?'Create account':'Log in';$('#switchCopy').innerHTML=signup?'Already have an account? <button class="text-btn" id="switchMode" type="button">Log in</button>':'New here? <button class="text-btn" id="switchMode" type="button">Create an account</button>';$('#switchMode').onclick=()=>{mode=signup?'login':'signup';authMode()}}
    authMode();
    $('#showPassword').onclick=()=>{const input=$('#password'),reveal=input.type==='password';input.type=reveal?'text':'password';$('#showPassword').textContent=reveal?'Hide':'Show';$('#showPassword').setAttribute('aria-pressed',String(reveal))};
    $('#authForm').onsubmit=e=>{e.preventDefault();const email=$('#email').value.trim().toLowerCase(), pass=$('#password').value, all=read();$('#authError').textContent='';if(mode==='signup'){if(all[email])return $('#authError').textContent='An account with this email already exists. Please log in.';all[email]={password:pass,data:blankData(email)};save(all);user=all[email].data;showOnboard()}else{if(!all[email]||all[email].password!==pass)return $('#authError').textContent='That email or password does not match.';user=all[email].data;user.plans.length?showApp():showOnboard()}};
    $$('#durationChoices .choice').forEach(b=>b.onclick=()=>{$$('#durationChoices .choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedMonths=+b.dataset.value;$('#durationNumber').value=selectedMonths;$('#durationUnit').value='months'});
    $('#toSubjects').onclick=()=>{const n=+$('#durationNumber').value||5,u=$('#durationUnit').value;selectedMonths=u==='days'?n/30:u==='years'?n*12:n; if(!$('#examName').value.trim())return toast('Add an exam or study goal first.');$('#setupOne').classList.add('hidden');$('#setupTwo').classList.remove('hidden');$('#s2').classList.add('active')};
    $('#anotherSubject').onclick=()=>{$('#starterSubjects').insertAdjacentHTML('beforeend','<div class="inline"><div class="field"><input class="subject-input" placeholder="Another subject"></div><div class="field"><select class="mode-input"><option>Daily practice</option><option>Concept revision</option><option>Mock tests</option><option>Reading</option></select></div></div>')};
    $('#finishSetup').onclick=()=>{const subjects=$$('.subject-input').map((x,i)=>({name:x.value.trim(),mode:$$('.mode-input')[i].value})).filter(x=>x.name);if(!subjects.length)return toast('Add at least one subject to begin.');const start=today(), end=new Date();end.setMonth(end.getMonth()+Math.round(selectedMonths));user.goal=$('#examName').value.trim();user.plans=subjects.map(x=>({...x,id:crypto.randomUUID(),start,end:end.toISOString().slice(0,10)}));persist();showApp()};
    function persist(){const all=read();all[user.email]={password:all[user.email]?.password||'',data:user};save(all)}
    function showOnboard(){$('#auth').classList.add('hidden');$('#onboard').classList.remove('hidden')};function showApp(){$('#auth').classList.add('hidden');$('#onboard').classList.add('hidden');$('#app').classList.remove('hidden');$('#quickNotes').value=user.quickNotes||'';render()}
    function tasks(){return user.plans||[]}function completion(date){return user.completed?.[date]||[]}function isDayDone(d){const ps=tasks();return ps.length>0&&ps.every(p=>completion(d).includes(p.id))}function streak(){let d=new Date();if(!isDayDone(today()))d.setDate(d.getDate()-1);let n=0;while(isDayDone(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
    function render(){const now=new Date(),hr=now.getHours();$('#greeting').textContent=hr<12?'Good morning, learner':hr<17?'Good afternoon, learner':'Good evening, learner';$('#profileName').textContent=user.goal||'Student';$('#profileEmail').textContent=user.email;$('#profileGoal').textContent=user.goal||'Student profile';$('#profileEmailCard').textContent=user.email;$('#profileGoalCard').textContent=user.goal||'Set a study goal';$('#avatar').textContent=(user.goal||user.email||'S').trim().charAt(0).toUpperCase();$('#dateLabel').textContent=fmtDate(now);const plans=tasks(),end=plans[0]?.end?new Date(plans[0].end+'T00:00'):now;const left=Math.max(0,Math.ceil((end-now)/86400000));$('#goalLine').textContent=user.goal?`Preparing for ${user.goal}`:'Your study plan is ready.';$('#heroTitle').textContent=user.goal||'Your focused season';$('#heroText').textContent=plans.length?`${plans.length} subject${plans.length>1?'s':''} in your active checklist. Small daily wins become serious progress.`:'Create a checklist to begin.';$('#daysLeft').textContent=`${left} day${left===1?'':'s'} left`;$('#streakValue').textContent=`${streak()} day${streak()===1?'':'s'}`;const done=completion(today()).length;$('#todayProgress').textContent=`${done} / ${plans.length}`;$('#progressBar').style.width=`${plans.length?done/plans.length*100:0}%`;renderTasks();renderCalendar();renderPlans();renderChart()}
    function renderChart(){const svg=$('#progressChart'),values=[],labels=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-i);const ds=d.toISOString().slice(0,10);values.push(completion(ds).length);labels.push(new Intl.DateTimeFormat('en',{weekday:'short'}).format(d))}const max=Math.max(1,tasks().length,...values),w=600,h=205,p={l:25,r:16,t:17,b:29},iw=w-p.l-p.r,ih=h-p.t-p.b,pts=values.map((v,i)=>[p.l+i*iw/6,p.t+ih-(v/max*ih)]),path=pts.map((q,i)=>`${i?'L':'M'}${q[0].toFixed(1)},${q[1].toFixed(1)}`).join(' '),area=`${path} L${pts[6][0]},${p.t+ih} L${pts[0][0]},${p.t+ih} Z`;let out='';for(let i=0;i<3;i++){const y=p.t+ih*i/2;out+=`<line class="chart-grid" x1="${p.l}" y1="${y}" x2="${w-p.r}" y2="${y}"/>`}out+=`<path class="chart-area" d="${area}"/><path class="chart-line" d="${path}"/>`;pts.forEach((q,i)=>{out+=`<circle class="chart-dot" cx="${q[0]}" cy="${q[1]}" r="4"/><text class="chart-label" text-anchor="middle" x="${q[0]}" y="${h-7}">${labels[i]}</text>`});svg.innerHTML=out;$('#weekTotal').textContent=`${values.reduce((a,b)=>a+b,0)} completed`}
    function openChecklists(){document.querySelector('[data-view="checklists"]').click();window.scrollTo({top:0,behavior:'smooth'})}
    function renderTasks(){const p=tasks(),wrap=$('#todayTasks');if(!p.length)return wrap.innerHTML='<div class="empty">Your checklist is empty. Add a subject in My checklists.</div>';wrap.innerHTML=p.map(x=>`<label class="plan-row openable" data-open-plan><input class="check" type="checkbox" data-task="${x.id}" ${completion(today()).includes(x.id)?'checked':''}><div><strong>${esc(x.name)}</strong><br><span>${esc(x.mode)} · Open full checklist</span></div><b class="tag">TODAY</b></label>`).join('');$$('[data-task]').forEach(c=>c.onchange=e=>{e.stopPropagation();const d=today(),arr=completion(d),id=c.dataset.task;user.completed[d]=c.checked?[...new Set([...arr,id])]:arr.filter(x=>x!==id);persist();render();toast(c.checked?'Nice work — progress saved!':'Task unchecked')});$$('[data-open-plan]').forEach(row=>row.onclick=e=>{if(e.target.matches('.check'))return;openChecklists()})}
    function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth();$('#monthTitle').textContent=new Intl.DateTimeFormat('en',{month:'long',year:'numeric'}).format(calDate);const first=new Date(y,m,1).getDay(), last=new Date(y,m+1,0).getDate(), prev=new Date(y,m,0).getDate(), cells=[];for(let i=0;i<first;i++)cells.push(`<span class="day muted">${prev-first+i+1}</span>`);for(let n=1;n<=last;n++){const ds=new Date(y,m,n).toISOString().slice(0,10), cls=ds===today()?'today':isDayDone(ds)?'done':'';cells.push(`<span class="day ${cls}">${n}</span>`)}while(cells.length%7)cells.push('<span class="day muted"></span>');$('#calendarDays').innerHTML=cells.join('');$('#calendarNote').textContent=isDayDone(today())?'Today is complete — your streak is protected.':'Finish every subject today to add a day to your streak.'}
    function renderPlans(){const p=tasks(), wrap=$('#plansList');wrap.innerHTML=p.length?p.map(x=>`<article class="plan-card"><div class="plan-card-top"><div><h3>${esc(x.name)}</h3><small>${esc(x.mode)} · checklist until ${new Date(x.end+'T00:00').toLocaleDateString('en',{month:'short',year:'numeric'})}</small></div><button class="delete" data-delete="${x.id}">Remove</button></div></article>`).join(''):'<div class="empty">No checklists yet.</div>';$$('[data-delete]').forEach(b=>b.onclick=()=>{user.plans=user.plans.filter(x=>x.id!==b.dataset.delete);persist();render();toast('Checklist removed')})}
    function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
    $('#addPlan').onsubmit=e=>{e.preventDefault();const name=$('#newSubject').value.trim(), months=+$('#newDuration').value;if(!name)return;const end=new Date();end.setMonth(end.getMonth()+months);user.plans.push({id:crypto.randomUUID(),name,mode:'Daily practice',start:today(),end:end.toISOString().slice(0,10)});persist();$('#newSubject').value='';render();toast('New checklist added')};
    $('#quickNotes').oninput=e=>{if(!user)return;user.quickNotes=e.target.value;persist()};
    $$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#dashboardView').classList.toggle('hidden',b.dataset.view!=='dashboard');$('#checklistsView').classList.toggle('hidden',b.dataset.view!=='checklists')});$('#goManage').onclick=openChecklists;$('#prevMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};$('#themeToggle').onclick=()=>applyTheme(document.body.classList.contains('dark')?'light':'dark');
